// This file is generated by Slice Machine. Update with care!

import SectionBuilding from './SectionBuilding';
import SectionBuilding2 from './SectionBuilding2';
import SectionHead from './SectionHead';
import SectionPlatform from './SectionPlatform';
import SectionReady from './SectionReady';
import SectionSolutions from './SectionSolutions';
import SectionTouch from './SectionTouch';

export {
	SectionBuilding,
	SectionBuilding2,
	SectionHead,
	SectionPlatform,
	SectionReady,
	SectionSolutions,
	SectionTouch,
};

export const components = {
	section_building: SectionBuilding,
	section_building2: SectionBuilding2,
	section_head: SectionHead,
	section_platform: SectionPlatform,
	section_ready: SectionReady,
	section_solutions: SectionSolutions,
	section_touch: SectionTouch,
};
