// This file is generated by Slice Machine. Update with care!
import SectionAbout from './SectionAbout';
import SectionBuilding from './SectionBuilding';
import SectionBuilding2 from './SectionBuilding2';
import SectionForm from './SectionForm';
import SectionHappening from './SectionHappening';
import SectionHead from './SectionHead';
import SectionJoin from './SectionJoin';
import SectionPlatform from './SectionPlatform';
import SectionReady from './SectionReady';
import SectionSolutions from './SectionSolutions';
import SectionTouch from './SectionTouch';
import SectionWho from './SectionWho';

export {
	SectionAbout,
	SectionBuilding,
	SectionBuilding2,
	SectionForm,
	SectionHappening,
	SectionHead,
	SectionJoin,
	SectionPlatform,
	SectionReady,
	SectionSolutions,
	SectionTouch,
	SectionWho,
};

export const components = {
	section_about: SectionAbout,
	section_building: SectionBuilding,
	section_building2: SectionBuilding2,
	section_form: SectionForm,
	section_happening: SectionHappening,
	section_head: SectionHead,
	section_join: SectionJoin,
	section_platform: SectionPlatform,
	section_ready: SectionReady,
	section_solutions: SectionSolutions,
	section_touch: SectionTouch,
	section_who: SectionWho,
};
