// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import MenuFooter from './MenuFooter';

export {
	Hero,
	MenuFooter,
};

export const components = {
	hero: Hero,
	menu_footer: MenuFooter,
};
